### ISSUE TITLE
5.x

### ISSUE THREAD

**Issue by michael-morris** [JeffreyHyer/bamboohr#1]
Would love 5.x support

**Comment by JeffreyHyer** [comment]
:+1: Thanks for the feedback @m-morris, I'll see if I can add support in the next week or so. It shouldn't be too difficult, just a matter of converting some PHP 7 shortcuts to longform (e.g. `[]` to `array()`, etc.)

I'll follow up here when it's done. Also if you'd like to contribute, feel free to submit a PR and/or comment here with any questions :)

**Comment by michael-morris** [comment]
Thanks @JeffreyHyer, 
I've updated to php7 so I'll be playing with this tonight.
No rush on the 5.x

**Comment by JeffreyHyer** [comment]
@Quazareth sounds great, let me know if you run into any issues.

Also note that the documentation is not up to date (it's on my todo list) but if you browse through the source under `src/Api/*.php` it should be fairly obvious what has been implemented.

If anything is missing that you absolutely need let me know, I'd be glad to prioritize it higher on the list.

**Comment by JeffreyHyer** [comment]
Closing this issue, with 5.x only getting older and 8 on the horizon I don't see a need to support it. If that changes feel free to open another issue and we can re-evaluate the situation.
