### ISSUE TITLE
Adding time-tracking data

### ISSUE THREAD

**Issue by alister** [JeffreyHyer/bamboohr#4]
Hi, this library looks to be more complete than the 'official' library, but I'm having issues adding time-tracking data (POSTing to the API). 

The Api\TimeTracking::addRecord sends post() what must be (by its parameter type) an array of data, but then that data is put in as form-params, while the headers indicate 'application/json' is being sent, without any way for json to be in the body.

Without the `array` typehint, I can put Json into the body for Guzzle to send [`->timetracking->addRecord(json_encode($times))`] 

I still can't get data posted to the API with the Json, but I'm hoping a sandbox account will help figure out why.

**Comment by JeffreyHyer** [comment]
@alister the headers should be indicating that the request is looking to accept a JSON **response** from the server but the data is sent as a form via POST.

The method in question `TimeTracking::addRecord()` accepts an array of data to POST to the server. 

For example:

```php
TimeTracking::addRecord([
    'timeTrackingId' => 'A_UNIQUE_ID',
    'employeeId' => 'EMPLOYEES_BAMBOOHR_ID',
    'dateHoursWorked' => 'YYYY-MM-DD',
    'rateType' => 'REG',
    'hoursWorked' => 8.00,
]);
```

Additional fields are accepted by the API, all the available fields as well as some notes that were very helpful for me to get up and running can be found here: https://www.bamboohr.com/api/documentation/time_tracking.php#addRequest

I hope that helps, if you have any other questions please feel free to ask. And thanks for the feedback!
