### ISSUE TITLE
1.0.5 does not exists at Packagist

### ISSUE THREAD

**Issue by migo315** [JeffreyHyer/bamboohr#7]
The last version does not exists at Packagist:
https://packagist.org/packages/jeffreyhyer/bamboohr

Maybe the webhook failed?

**Comment by migo315** [comment]
I think this caused by the line at composer.json:
`"version": "1.0.4",`

You don't need the version in your composer.json. Composer and Packagist can work with tags. I recommend to remove this line from composer.json and only work with tags (you already working with tags)

**Comment by JeffreyHyer** [comment]
Thanks for the heads up, it seems that tagging a release through the GitHub UI doesn't trigger the webhook properly for packagist. I've fixed the issue with the 1.0.6 release (which is functionally identical to v1.0.5, just a version/tag bump).
